version: '3.8'

services:
  db:
    container_name: "tl_notes_db"
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_PSQL_NAME}
      POSTGRES_USER: ${DB_PSQL_USER}
      POSTGRES_PASSWORD: ${DB_PSQL_PASSWORD}


  redis:
    image: redis:latest
    container_name: "tl_notes_redis"
    volumes:
      - /home/tl_notes/redis_data:/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  celery:
    build: .
    command: "./wait-for-it.sh db:5432 -t 30 -- celery -A tl_notes worker --loglevel=info --concurrency=1"
    volumes:
      - .:/app
    env_file:
      - ../env/.env
    depends_on:
      - redis
      - db

  flower:
    build: .
    container_name: "tl_notes_flower"
    command: celery -A tl_notes flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - ../env/.env
    depends_on:
      - redis
      - db

  web:
    build: .
    container_name: "tl_notes_web"
    entrypoint: [ "./entrypoint.sh", "db", "5432" ]
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    env_file:
      - ../env/.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: