# Generated by Django 5.1.1 on 2024-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="task_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="Task ID"),
        ),
    ]
