# Generated by Django 5.1.1 on 2024-09-19 22:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0002_note_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
