# Generated by Django 5.1.1 on 2024-09-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0004_dailyreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="in_progress",
            field=models.BooleanField(default=True),
        ),
    ]
