# Generated by Django 5.1.1 on 2024-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0007_alter_note_created_at_alter_note_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(null=True, verbose_name="Created at"),
        ),
    ]
